# Generated by Django 3.1.6 on 2021-03-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='iselect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('begin_date', models.DateField(blank=True, null=True, verbose_name='开始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日')),
                ('begin_time', models.TimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='结束时间')),
                ('datanum', models.IntegerField(blank=True, null=True, verbose_name='数据量')),
                ('kmin', models.IntegerField(blank=True, null=True, verbose_name='数据量')),
            ],
        ),
        migrations.CreateModel(
            name='sto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='交易日')),
                ('code', models.CharField(max_length=200)),
                ('open', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='开盘价')),
                ('close', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='收盘价')),
                ('high', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='最高价')),
                ('low', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='最低价')),
                ('volume', models.BigIntegerField(blank=True, null=True, verbose_name='交易量')),
            ],
            options={
                'verbose_name': '日K线',
                'verbose_name_plural': '日K线',
            },
        ),
    ]
